### PR TITLE
Documentation for available policies

### PR DESCRIPTION
**Pull request by rickygodoy**
- Go script to crawl policies directory and generate markdown
-  GitHub Action to trigger the script when pushing to master

The script needs two parameters: **policies folder and output file path**, and it's possible to test the script locally (go run) and even test GH action locally using [act](https://github.com/nektos/act)

The idea here is to have a public markdown file with a list of policies to be referred from somewhere else and serve as documentation as well.

Not sure if it's the best approach, I'm open to suggestions :)

### CODE REVIEW

**Review by danielmarzini — APPROVED** [review]
I really like this, approving. Please, even in another PR if you want, a test would be awesome!

**Review by mikouaj — COMMENTED** [review]
Great job!
My only doubt is about having documentation inside the `policy` package, I would rather have it in 'outputs' (even that it is not an evaluation results collector).

**Comment by rickygodoy** [comment]
Apologize for broken build, already fixed it.

Also changed CLI usage to `./gke-policy generate policy-docs -o your-file-name.md`

**Review by mikouaj — APPROVED** [review]
LGTM!

**Pull request merged**
