### PR TITLE
Added GKE Benchmark 1.4 Controls

### PR DESCRIPTION
**Pull request by spawar-apex**
- Added Node CoS & Cluster Intranode Visibility control to the GKE Policies.

### CODE REVIEW

**Review by mikouaj — COMMENTED** [review]
Hi @spawar-apex, thank you for this great contribution on intranode visibility policy!

FYI the table in a `gke-policies-v2/README.md` file can be generated automatically by running generate policy-docs command, i.e:
```
./gke-policy generate policy-docs -local-policy-dir ./gke-policies-v2 -f generated-policy-docs.md
```
The generated table takes policies and their metadata from a given directory. This helps to avoid human errors. For instance, I think that `Container-Optimized OS` policy was already in this `README.md` as `Use Container-Optimized OS`.

**Comment by spawar-apex** [comment]
> Hi @spawar-apex, thank you for this great contribution on intranode visibility policy!
> 
> FYI the table in a `gke-policies-v2/README.md` file can be generated automatically by running generate policy-docs command, i.e:
> 
> ```
> ./gke-policy generate policy-docs -local-policy-dir ./gke-policies-v2 -f generated-policy-docs.md
> ```
> 
> The generated table takes policies and their metadata from a given directory. This helps to avoid human errors. For instance, I think that `Container-Optimized OS` policy was already in this `README.md` as `Use Container-Optimized OS`.

Thank you @mikouaj for sharing the details. I'll make necessary updates and push the PR.

**Review by mikouaj — COMMENTED** [review]
Thanks @spawar-apex, please do not commit the `generated-policy-docs.md` file. Simply copy the content of the generated file to the `gke-policies-v2/README.md` instead, below the 
`<!-- BEGIN POLICY-DOC -->` statement.

**Review by mikouaj — APPROVED** [review]
Great job @spawar-apex, thank you for this contribution!

**Pull request merged**
